hunt_kingdom_homepage:
    path:     /
    defaults: { _controller: HuntKingdomBundle:Default:index }

    #Animal
hunt_kingdom_ajoutAnimal:
    path:     /ajoutAnimal
    defaults: { _controller: HuntKingdomBundle:Animal:ajoutAnimal }
hunt_kingdom_updateAnimal:
        path:     /updateAnimal{id}
        defaults: { _controller: HuntKingdomBundle:Animal:updateAnimal }
hunt_kingdom_deleteAnimal:
    path:     /deleteAnimal{id}
    defaults: { _controller: HuntKingdomBundle:Animal:deleteAnimal }
hunt_kingdom_showAnimal:
    path:     /showAnimal
    defaults: { _controller: HuntKingdomBundle:Animal:showAnimal }
hunt_kingdom_frontAnimal:
    path:     /frontAnimal
    defaults: { _controller: HuntKingdomBundle:Animal:frontAnimal }

    #Season
hunt_kingdom_ajoutSeason:
    path:     /ajoutSeason
    defaults: { _controller: HuntKingdomBundle:Season:ajoutSeason }
hunt_kingdom_updateSeason:
        path:     /updateSeason{id}
        defaults: { _controller: HuntKingdomBundle:Season:updateSeason }
hunt_kingdom_deleteSeason:
    path:     /deleteSeason{id}
    defaults: { _controller: HuntKingdomBundle:Season:deleteSeason }
hunt_kingdom_showSeason:
    path:     /showSeason
    defaults: { _controller: HuntKingdomBundle:Season:showSeason }
hunt_kingdom_frontSeason:
    path:     /frontSeason
    defaults: { _controller: HuntKingdomBundle:Season:frontSeason }

    #Commande
hunt_kingdom_showCommande:
    path:     /showCommande
    defaults: { _controller: HuntKingdomBundle:Commande:showCommande }
hunt_kingdom_showCommandeUser:
    path:     /showCommandeUser
    defaults: { _controller: HuntKingdomBundle:Commande:showCommandeUser }